// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: oneOfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shape struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Shape:
	//
	//	*Shape_Circle
	//	*Shape_Rectangle
	//	*Shape_Triangle
	Shape isShape_Shape `protobuf_oneof:"shape"`
}

func (x *Shape) Reset() {
	*x = Shape{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneOfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shape) ProtoMessage() {}

func (x *Shape) ProtoReflect() protoreflect.Message {
	mi := &file_oneOfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shape.ProtoReflect.Descriptor instead.
func (*Shape) Descriptor() ([]byte, []int) {
	return file_oneOfs_proto_rawDescGZIP(), []int{0}
}

func (m *Shape) GetShape() isShape_Shape {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (x *Shape) GetCircle() *Circle {
	if x, ok := x.GetShape().(*Shape_Circle); ok {
		return x.Circle
	}
	return nil
}

func (x *Shape) GetRectangle() *Rectangle {
	if x, ok := x.GetShape().(*Shape_Rectangle); ok {
		return x.Rectangle
	}
	return nil
}

func (x *Shape) GetTriangle() *Triangle {
	if x, ok := x.GetShape().(*Shape_Triangle); ok {
		return x.Triangle
	}
	return nil
}

type isShape_Shape interface {
	isShape_Shape()
}

type Shape_Circle struct {
	Circle *Circle `protobuf:"bytes,1,opt,name=circle,proto3,oneof"`
}

type Shape_Rectangle struct {
	Rectangle *Rectangle `protobuf:"bytes,2,opt,name=rectangle,proto3,oneof"`
}

type Shape_Triangle struct {
	Triangle *Triangle `protobuf:"bytes,3,opt,name=triangle,proto3,oneof"`
}

func (*Shape_Circle) isShape_Shape() {}

func (*Shape_Rectangle) isShape_Shape() {}

func (*Shape_Triangle) isShape_Shape() {}

type Circle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Radius float32 `protobuf:"fixed32,1,opt,name=radius,proto3" json:"radius,omitempty"`
}

func (x *Circle) Reset() {
	*x = Circle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneOfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Circle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Circle) ProtoMessage() {}

func (x *Circle) ProtoReflect() protoreflect.Message {
	mi := &file_oneOfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Circle.ProtoReflect.Descriptor instead.
func (*Circle) Descriptor() ([]byte, []int) {
	return file_oneOfs_proto_rawDescGZIP(), []int{1}
}

func (x *Circle) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type Rectangle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  float32 `protobuf:"fixed32,1,opt,name=width,proto3" json:"width,omitempty"`
	Height float32 `protobuf:"fixed32,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneOfs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_oneOfs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_oneOfs_proto_rawDescGZIP(), []int{2}
}

func (x *Rectangle) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rectangle) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Triangle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base   float32 `protobuf:"fixed32,1,opt,name=base,proto3" json:"base,omitempty"`
	Height float32 `protobuf:"fixed32,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Triangle) Reset() {
	*x = Triangle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneOfs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Triangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triangle) ProtoMessage() {}

func (x *Triangle) ProtoReflect() protoreflect.Message {
	mi := &file_oneOfs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triangle.ProtoReflect.Descriptor instead.
func (*Triangle) Descriptor() ([]byte, []int) {
	return file_oneOfs_proto_rawDescGZIP(), []int{3}
}

func (x *Triangle) GetBase() float32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *Triangle) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_oneOfs_proto protoreflect.FileDescriptor

var file_oneOfs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x73, 0x22, 0xaf, 0x01, 0x0a,
	0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f,
	0x6e, 0x65, 0x4f, 0x66, 0x73, 0x2e, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x06,
	0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x74, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12,
	0x34, 0x0a, 0x08, 0x74, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x73,
	0x2e, 0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x08, 0x74, 0x72, 0x69,
	0x61, 0x6e, 0x67, 0x6c, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x22, 0x20,
	0x0a, 0x06, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73,
	0x22, 0x39, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x36, 0x0a, 0x08, 0x54,
	0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneOfs_proto_rawDescOnce sync.Once
	file_oneOfs_proto_rawDescData = file_oneOfs_proto_rawDesc
)

func file_oneOfs_proto_rawDescGZIP() []byte {
	file_oneOfs_proto_rawDescOnce.Do(func() {
		file_oneOfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneOfs_proto_rawDescData)
	})
	return file_oneOfs_proto_rawDescData
}

var file_oneOfs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_oneOfs_proto_goTypes = []interface{}{
	(*Shape)(nil),     // 0: proto.oneOfs.Shape
	(*Circle)(nil),    // 1: proto.oneOfs.Circle
	(*Rectangle)(nil), // 2: proto.oneOfs.Rectangle
	(*Triangle)(nil),  // 3: proto.oneOfs.Triangle
}
var file_oneOfs_proto_depIdxs = []int32{
	1, // 0: proto.oneOfs.Shape.circle:type_name -> proto.oneOfs.Circle
	2, // 1: proto.oneOfs.Shape.rectangle:type_name -> proto.oneOfs.Rectangle
	3, // 2: proto.oneOfs.Shape.triangle:type_name -> proto.oneOfs.Triangle
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_oneOfs_proto_init() }
func file_oneOfs_proto_init() {
	if File_oneOfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oneOfs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shape); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneOfs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Circle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneOfs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rectangle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneOfs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Triangle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oneOfs_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Shape_Circle)(nil),
		(*Shape_Rectangle)(nil),
		(*Shape_Triangle)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneOfs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneOfs_proto_goTypes,
		DependencyIndexes: file_oneOfs_proto_depIdxs,
		MessageInfos:      file_oneOfs_proto_msgTypes,
	}.Build()
	File_oneOfs_proto = out.File
	file_oneOfs_proto_rawDesc = nil
	file_oneOfs_proto_goTypes = nil
	file_oneOfs_proto_depIdxs = nil
}
